_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 49
                - 51
                - 55
                - 95
                - 97
                - 105
            "2":
                - 49
                - 51
                - 55
                - 95
                - 97
                - 105
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": darwin-arm64
